qt_add_executable(TraceScopeLiveLogGenerator
    main.cpp
    LiveLogRecord.h
    LiveLogScenarioStep.h
    LiveLogScenario.h
    LiveLogScenarioLoader.h
    LiveLogScenarioLoader.cpp
    ILogRecordRenderer.h
    renderers/JsonLinesRenderer.h
    renderers/JsonLinesRenderer.cpp
    LiveLogScenarioPlayer.h
    LiveLogScenarioPlayer.cpp
    renderers/DelimitedTextRenderer.h
    renderers/DelimitedTextRenderer.cpp
    LogRecordRendererFactory.h
    LogRecordRendererFactory.cpp
    renderers/KeyValueTextRenderer.h
    renderers/KeyValueTextRenderer.cpp
    renderers/StructuredJsonRenderer.h
    renderers/StructuredJsonRenderer.cpp
    renderers/StructuredXmlRenderer.h
    renderers/StructuredXmlRenderer.cpp
    renderers/WindowsEventXmlRenderer.h
    renderers/WindowsEventXmlRenderer.cpp
    renderers/SyslogRenderer.h
    renderers/SyslogRenderer.cpp
)

target_link_libraries(TraceScopeLiveLogGenerator
    PRIVATE
        Qt6::Core
)